'\" t
.\"     Title: Bitcoin Toolkit
.\"    Author: [see the "Authors" section]
.\"      Date: 01/18/2023
.\"    Manual: Bitcoin Toolkit Manual
.\"    Source: Bitcoin Toolkit 3.0.0
.\"  Language: English
.\"
.TH "BTK" "1" "01/18/2023" "Bitcoin Toolkit 3.0.0" "Bitcoin Toolkit Manual"
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
btk-node \- Interface with a bitcoin node.
.SH "SYNOPSIS"
.sp
.nf
\fIbtk\fR \fInode\fR -h <host> [-p <port>]
.fi
.sp
.SH "DESCRIPTION"
.sp
Connect and send a bitcoin 'version' message to a remote bitcoin node and display the resulting verison info. Bitcoin's version information contains the bitcoin protocol version, available services, current block height, user agent string, and more.

.sp
.SH "OPTIONS"

.PP
\-h <host>, --hostname=<host>
.RS 4
Specify the hostname or IP of a remote bitcoin node.
.RE

.PP
\-p <port>, --port=<port>
.RS 4
Specify the port number or service of a remote bitcoin node. Default is port 8333.
.RE

.sp
.SH "SEE ALSO"

.sp
\fBbtk\fR(1)