'\" t
.\"     Title: Bitcoin Toolkit
.\"    Author: [see the "Authors" section]
.\"      Date: 01/18/2023
.\"    Manual: Bitcoin Toolkit Manual
.\"    Source: Bitcoin Toolkit 3.1.2
.\"  Language: English
.\"
.TH "BTK-VERSION" "1" "12/11/2023" "Bitcoin Toolkit 3.1.2" "Bitcoin Toolkit Manual"
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
btk-version \- Display btk version info.
.SH "SYNOPSIS"
.sp
.nf
\fIbtk\fR \fIversion\fR
.fi
.sp
.SH "DESCRIPTION"
.sp
Print btk version information.

.sp
.SH "OPTIONS"

.PP
\-L, --out-format=list
.RS 4
Format the output as a list of ascii strings delimited by a newline character.
.RE

.PP
\-J, --out-format=json
.RS 4
Format the output as a list of ascii strings contained within a json array. This is the default output format when no other is specified.
.RE

.sp
.SH "SEE ALSO"

.sp
\fBbtk\fR(1)