'\" t
.\"     Title: Bitcoin Toolkit
.\"    Author: [see the "Authors" section]
.\"      Date: 01/18/2023
.\"    Manual: Bitcoin Toolkit Manual
.\"    Source: Bitcoin Toolkit 3.0.0
.\"  Language: English
.\"
.TH "BTK" "1" "01/18/2023" "Bitcoin Toolkit 3.0.0" "Bitcoin Toolkit Manual"
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
btk-addressdb \- Create and query database for address balance data.
.SH "SYNOPSIS"
.sp
.nf
\fIbtk\fR \fIaddressdb\fR -p <path>
.fi
.sp
.SH "DESCRIPTION"
.sp
Description Needed.

.sp
.SH "OPTIONS"

.PP
\-c
.RS 4
Create a database containing the balance of all addresses contained in the UTXO database of bitcoin core. This process can take up to an hour to complete.
.RE

.PP
\-p <path>
.RS 4
Specify the path to bitcoin core's utxo database. By default, it is located in the \"chainstate\" directory within bitcoin core's default installation directory.
.RE

.PP
\-P <path>
.RS 4
Specify the path to the address balance database.
.RE

.sp
.SH "SEE ALSO"

.sp
\fBbtk\fR(1), \fBbtk-pubkey\fR(1), \fBbtk-address\fR(1)