."     Title: btk-pubkey
."    Author: Brian Barto
."      Date: 01/22/2018
.TH "btk-pubkey" 1 "01/23/2018" "1.0" "btk-pubkey User Manual"
.SH NAME
btk-pubkey - Calculate public keys from private keys
.SH SYNOPSIS
btk pubkey [-w | -h | -r]
           [-A | -H | -R]
           [-T]
           [-N]
.SH DESCRIPTION
The pubkey command will calculate the public key from a given private key. It requires as input a private key string in the format specified by the input options (see OPTIONS). It then outputs the public key in the format specified by the output options (see OPTIONS).
.PP
Private keys should be provided as input in either WIP, hexidecimal, or raw (unsigned char string) format. These formats should correspond to the output options from btk-privkey. Thus the output from btk-privkey can then be used as input for btk-pubkey.
.SH OPTIONS
.B Input Options
.TP
.B -w
Supply a private key as input in WIF format.
.TP
.B -h
Supply a private key as input in hexidecimal format.
.TP
.B -r
Supply a private key as input in raw (unsigned char string) format.
.PP
.B Output Options
.TP
.B -A
Output the public key in standard bitcoin address format. The address will be compressed unless a private key is supplied in uncompresed WIF format. This option is the default when no other output option is specified.
.TP
.B -H
Output the public key in hexidecimal format.
.TP
.B -R
Output the public key in raw (unsigned char string) format.
.PP
.B Testnet Options
.TP
.B -T
Format the output for testnet.
.PP
.B Misc Options
.TP
.B -N
Append a newline character to the output so the command prompt starts on the next line. This is generally used for easier reading.
.SH "SEE ALSO"
btk-privkey(1)
.SH AUTHOR
Brian Barto ( https://github.com/bartobri )
